spring:
  application:
    name: api-gateway

server:
  port: 8000
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false        

zuul:
    prefix: /api-gateway
    routes:
        das-boot:
            path: /das-boot/**
            serviceId: das-boot
            stripPrefix: false
            
        jooq-madhan:
            path: /jooq-madhan/**
            serviceId: jooq-madhan
            stripPrefix: false